### ISSUE TITLE
Rozszerzenie Bazy danych

### ISSUE THREAD

**Issue by Leshens** [Leshens/LetsEatRestauantAPI#18]
## Dodanie pól do restauracji:

- Godziny otwarcia; String; 12:00 - 23:00 
- link do zdjęcia restauracji
- link do strony internetowej
- długość geograficzna; Int
- szerokość geograficzna; Int
- telefon

## API
- Zmienić GETa z ID restauracji na GETa z Tokenem
- Weryfikacja tokenu w tabeli z tokenem w headerze HTTPka przy edycji i usuwaniu danych

**Comment by Leshens** [comment]
Request: proxy patter
Repository: unit of work pattern
Adapter Pattern

**Comment by Leshens** [comment]
TODO:
@Leshens 
- contrakty DTO

@sugarvalley 
-1) controller
-2) service

**Comment by sugarvalley** [comment]
done on branch https://github.com/Leshens/LetsEatRestauantAPI/pull/31
